### ISSUE TITLE
document.querySelectorAll returns stale results

### ISSUE THREAD

**Issue by Scarysize** [jsdom/jsdom#2519]
### Basic info:

- **Node.js version:** v8.11.4
- **jsdom version:** v13.2.0 (bug is also present in v11.12.0)

### Minimal reproduction case

```js
const jsdom = require('jsdom');
const {JSDOM} = jsdom;

function append(html) {
  document.body.innerHTML = html;
}

function clean() {
  document.body.innerHTML = '';
}

const dom = new JSDOM(`<!DOCTYPE html>`);
const document = dom.window.document;

const fixtures = {
  a: '<a id="link-a" class="test">a link</a>',
  b: '<a id="link-b" class="test"><img src="foo.jpg" /></a>'
};

append(fixtures.a);
console.log(document.body.innerHTML);
// should log "link-a"
document.querySelectorAll('a.test').forEach(node => console.log(node.id));
clean();

append(fixtures.b);
console.log(document.body.innerHTML);
// should log "link-b"
document.querySelectorAll('a.test').forEach(node => console.log(node.id));
clean();

append(fixtures.a);
console.log(document.body.innerHTML);
// should log "link-a", but logs "link-b"
document.querySelectorAll('a.test').forEach(node => console.log(node.id));
clean();
```

### How does similar code behave in browsers?

https://jsbin.com/fobuxoceva/edit?js,console

Pretty much what the title says. `document.querySelectorAll` returns Nodes which have been removed already. I suspect this is an issue of memoization of queries: If the last `querySelectorAll('a.test')` is changed to `querySelectorAll('.test')` (parameters are different from previous calls), it works as expected. AFAIK memoization for `querySelectorAll` has been removed here: https://github.com/jsdom/jsdom/commit/bfb08434f540491591aace17b302816f146dd4ef

### Context

We discovered this while move old jasmine tests over to `jest` which uses jsdom. I guess adding and removing  DOM nodes between unit tests isn't anything exotic.

**Comment by Scarysize** [comment]
Did some digging and the issue seems to be in `nwsapi`: 

https://github.com/jsdom/jsdom/blob/16d3913eea0360c7757e75f7e266c3873c85b7dd/lib/jsdom/living/helpers/selectors.js#L36-L40

If the `LIVECACHE` option (https://github.com/dperini/nwsapi#configure-options-) is set to `false`, `querySelectorAll` returns the correct result.

**Comment by domenic** [comment]
Some discussion going on in https://github.com/dperini/nwsapi/pull/23; hopefully that gets fixed in nwsapi as this kind of breaking change in a minor version is not really OK :(.

**Comment by franzneubert0815** [comment]
Looks like this was fixed upstream and publish as nwsapi@2.1.1:

https://github.com/dperini/nwsapi/commit/a5417cd77e496effc914ac1c1f87befbf59aa288

**Comment by franzneubert0815** [comment]
When reinstalling the latest jsdom (and jest), you will automatically receive the fixed nwsapi version. The above code now works as expected, feel free to close this one.

**Comment by domenic** [comment]
Thanks for the report. Let's keep this open until we can add a test to prevent regressions.

**Comment by sscaetite** [comment]
I'm still having issues with querySelector all:

My code:

`return htmlObject.window.document.querySelectorAll('div');`

My HTML:
```
<div>someone</div>
<div>help</div>
<div>me</div>
<div>please</div>
<div>im</div>
<div>confuse</div>
```

The response:

> NodeList {
>   '0': HTMLDivElement {},
>   '1': HTMLDivElement {},
>   '2': HTMLDivElement {},
>   '3': HTMLDivElement {},
>   '4': HTMLDivElement {},
>   '5': HTMLDivElement {} }
>

**Comment by franzneubert0815** [comment]
@sscaetite This looks correct and unrelated to this issue. You shouldn't trust console.log to display the contents of your `div`s. Try to log the actual HTML using `node.outerHTML`.
